CREATE DATABASE IF NOT EXISTS krug_pi CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE krug_pi;
CREATE TABLE IF NOT EXISTS trial_requests (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(254) NOT NULL,
    phone VARCHAR(40) NOT NULL,
    courses VARCHAR(100) NOT NULL,
    message TEXT NOT NULL,
    consent BOOLEAN NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
